name: Build pycairo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    environment: pypi

    steps:
      - run: git clone --depth=1 https://github.com/pygobject/pycairo .

      - name: Build wheels
        uses: https://github.com/pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BEFORE_ALL_LINUX: "apt-get install -yqq libcairo2"
          CIBW_BUILD: "cp31{0..3}-manylinux_{x86_64,aarch64}"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
 
      - name: Publish package distributions to Forgejo
        uses: https://github.com/pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://git.weddingfactory.eu/api/packages/cmwedding/pypi/simple
          user: cmwedding-bot
          password: ${{ secrets.FORGEJO_TOKEN }}
          packages-dir: ./wheelhouse
          skip-existing: true

