name: Build pycairo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - run: git clone --depth=1 https://github.com/pygobject/pycairo --branch v1.28.0 .

      - name: Build wheels
        uses: https://github.com/pypa/cibuildwheel@v2.23.3
        env:
          CIBW_BEFORE_ALL_LINUX: "dnf install -y cairo-devel"
          CIBW_BUILD: "cp31{0..3}-manylinux_{x86_64,aarch64}"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
 
      - name: Publish package distributions to Forgejo
        run: |
          pip3 install twine
          python3 -m twine upload ./wheelhouse/*
        env:
          TWINE_REPOSITORY_URL: https://git.weddingfactory.eu/api/packages/cmwedding/pypi/simple
          TWINE_USER: cmwedding-bot
          TWINE_PASSWORD: ${{ secrets.FORGEJO_TOKEN }}

