name: Build runbot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/runbot.yaml"
      - "runbot/pyproject.toml"

env:
  ODOO_VERSION: "19.0"
  REPOSITORY_URL: https://cmwedding-bot:${{ secrets.FORGEJO_TOKEN }}@git.weddingfactory.eu/api/packages/cmwedding/pypi

jobs:
  build:
    name: Build runbot wheel
    runs-on: ubuntu-latest

    steps:
      - id: check
        uses: cmwedding-it/wheels@check-action
        with:
          pypi-base-url: ${{ env.REPOSITORY_URL }}
          pypi-package: odoo-addons-runbot
          github-repository: "odoo/runbot"
          unstable-branch: ${{ env.ODOO_VERSION }}

      - name: Check out self
        uses: actions/checkout@v4

      - name: Check out source
        if: steps.check.outputs.version != ''
        run: git clone --depth=1 https://github.com/odoo/runbot --branch ${{ env.ODOO_VERSION }} src/

      - name: Prepare package
        if: steps.check.outputs.version != ''
        run: |
          cp runbot/pyproject.toml src/
          sed -i 's/%s/${{ steps.check.outputs.version }}/' src/pyproject.toml

      - name: Setup dependencies
        if: steps.check.outputs.version != ''
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install hatch hatch-odoo twine

      - name: Build wheel
        if: steps.check.outputs.version != ''
        run: |
          source .venv/bin/activate
          cd src/
          hatch build -t wheel

      - name: Publish package
        if: steps.check.outputs.version != ''
        env:
          TWINE_REPOSITORY_URL: ${{ env.REPOSITORY_URL }}
          TWINE_NON_INTERACTIVE: 1
        run: |
          source .venv/bin/activate
          python3 -m twine upload ./src/dist/*
